CREATE TABLE feed(
	`fid` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	`fname` CHARACTER(10) NOT NULL,
	`url` VARCHAR(255) NOT NULL,
	`state` TINYINT(1) DEFAULT 0,
	`cid` INTEGER NOT NULL
);

CREATE TABLE feed_category(
	`cid` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	`cname` CHARACTER(10) NOT NULL
);
